name: test

on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    name: test
    strategy:
      fail-fast: false
      matrix:
        # 3.9 is omitted since there's no stackvana build for py3.9
        pyver: ["3.8", "3.10"]

    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v3

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.pyver }}
          channels: conda-forge
          channel-priority: strict
          show-channel-urls: true

      - name: Install DM stack and mypy with conda/mamba
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes
          conda install -q mamba

          mamba install -q stackvana=0
          mamba install -q mypy

      - name: Build and run tests
        shell: bash -l {0}
        run: |
          setup -v -r .
          scons

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v2
        with:
          file: ./coverage.xml

      - name: Run MyPy
        shell: bash -l {0}
        run: |
          setup -v -r .
          mypy python/ tests/
